window.AL = window.AL || {};

AL.products = [
  {
    id: "ase-2026",
    sku: "AL-ASE-2026",
    slug: "2026-american-silver-eagle",
    name: "2026 American Silver Eagle",
    lot: "2026 ASE BU",
    category: "government",
    troyOz: 1,
    purity: ".999",
    mint: "U.S. Mint",
    stock: 24,
    featured: true,
    lowestPremium: false,
    clearance: false,
    finish: "Brilliant uncirculated",
    bin: "Kent-A-01",
    reorderPoint: 6,
    premiumTiers: [{ min: 1, premium: 5.5 }, { min: 20, premium: 5.1 }],
    blurb: "The flagship U.S. bullion coin. One troy ounce, legal tender, Walking Liberty obverse."
  },
  {
    id: "maple-1oz",
    sku: "AL-MAPLE-1",
    slug: "canadian-maple-leaf-1oz",
    name: "Canadian Maple Leaf 1 oz",
    lot: "Maple 1 oz",
    category: "government",
    troyOz: 1,
    purity: ".9999",
    mint: "Royal Canadian Mint",
    stock: 30,
    featured: true,
    lowestPremium: false,
    clearance: false,
    finish: "Bullion",
    bin: "Kent-A-02",
    reorderPoint: 8,
    premiumTiers: [{ min: 1, premium: 3.5 }, { min: 25, premium: 3.15 }],
    blurb: "Four nines fine. Radial lines and a micro-engraved maple leaf for anti-counterfeit work."
  },
  {
    id: "britannia-1oz",
    sku: "AL-BRIT-1",
    slug: "britannia-1oz",
    name: "Britannia 1 oz",
    lot: "Britannia 1 oz",
    category: "government",
    troyOz: 1,
    purity: ".999",
    mint: "Royal Mint",
    stock: 18,
    featured: true,
    lowestPremium: false,
    clearance: false,
    finish: "Bullion",
    bin: "Kent-A-03",
    reorderPoint: 5,
    premiumTiers: [{ min: 1, premium: 4 }, { min: 20, premium: 3.6 }],
    blurb: "British sovereign coin. Latent image and surface animation on current-year strikes."
  },
  {
    id: "generic-1oz",
    sku: "AL-GEN-1",
    slug: "generic-1oz-round",
    name: "Generic 1 oz round",
    lot: "Generic rounds",
    category: "generic",
    troyOz: 1,
    purity: ".999",
    mint: "Secondary / mixed",
    stock: 80,
    featured: true,
    lowestPremium: true,
    clearance: false,
    finish: "Minted round",
    bin: "Kent-B-01",
    reorderPoint: 20,
    premiumTiers: [{ min: 1, premium: 1.75 }, { min: 50, premium: 1.4 }],
    blurb: "Lowest-premium ounce on the board. Mixed hallmarks, all .999, counted and weighed here."
  },
  {
    id: "bar-5oz",
    sku: "AL-BAR-5",
    slug: "generic-5oz-bar",
    name: "Generic 5 oz bar",
    lot: "5 oz minted",
    category: "bar",
    troyOz: 5,
    purity: ".999",
    mint: "Generic",
    stock: 12,
    featured: false,
    lowestPremium: true,
    clearance: false,
    finish: "Minted bar",
    bin: "Kent-B-02",
    reorderPoint: 3,
    premiumTiers: [{ min: 1, premium: 2.75 }, { min: 5, premium: 2.4 }],
    blurb: "Five ounces in one piece. Easier to store than five rounds, tighter than most coins."
  },
  {
    id: "bar-10oz",
    sku: "AL-BAR-10",
    slug: "generic-10oz-bar",
    name: "Generic 10 oz bar",
    lot: "10 oz minted",
    category: "bar",
    troyOz: 10,
    purity: ".999",
    mint: "Generic",
    stock: 9,
    featured: false,
    lowestPremium: true,
    clearance: false,
    finish: "Minted bar",
    bin: "Kent-B-03",
    reorderPoint: 2,
    premiumTiers: [{ min: 1, premium: 2.5 }, { min: 5, premium: 2.2 }],
    blurb: "The stacker default. Ten ounces, serial if present, premium well under sovereign coin."
  },
  {
    id: "bar-100oz",
    sku: "AL-BAR-100",
    slug: "generic-100oz-bar",
    name: "Generic 100 oz bar",
    lot: "100 oz cast",
    category: "bar",
    troyOz: 100,
    purity: ".999",
    mint: "Generic / recast",
    stock: 2,
    featured: false,
    lowestPremium: true,
    clearance: false,
    finish: "Cast bar",
    bin: "Kent-C-01",
    reorderPoint: 1,
    premiumTiers: [{ min: 1, premium: 1.75 }],
    blurb: "Weight over pretty. Cast, marked, heavy. Signature required on the box."
  },
  {
    id: "bar-kilo",
    sku: "AL-BAR-KG",
    slug: "kilo-silver-bar",
    name: "1 kilo silver bar",
    lot: "Kilo minted",
    category: "bar",
    troyOz: 32.15,
    purity: ".999",
    mint: "Generic",
    stock: 3,
    featured: false,
    lowestPremium: false,
    clearance: false,
    finish: "Minted bar",
    bin: "Kent-C-02",
    reorderPoint: 1,
    premiumTiers: [{ min: 1, premium: 2 }],
    blurb: "32.15 troy ounces in a single minted kilo. Clean edges, stamped weight and fineness."
  },
  {
    id: "art-lane",
    sku: "AL-ART-LANE",
    slug: "lane-mark-art-round",
    name: "Lane Mark art round",
    lot: "Lane Mark 01",
    category: "art",
    troyOz: 1,
    purity: ".999",
    mint: "Private",
    stock: 14,
    featured: false,
    lowestPremium: false,
    clearance: false,
    finish: "Proof-like",
    bin: "Kent-D-01",
    reorderPoint: 4,
    premiumTiers: [{ min: 1, premium: 8 }],
    blurb: "House design. One ounce, proof-like, numbered on the package. Metal first, souvenir second."
  },
  {
    id: "ase-cull",
    sku: "AL-ASE-CULL",
    slug: "silver-eagle-cull",
    name: "American Silver Eagle — cull / random",
    lot: "ASE cull",
    category: "government",
    troyOz: 1,
    purity: ".999",
    mint: "U.S. Mint",
    stock: 16,
    featured: false,
    lowestPremium: false,
    clearance: true,
    finish: "Circulated / spotted",
    bin: "Kent-D-02",
    reorderPoint: 4,
    premiumTiers: [{ min: 1, premium: 2.25 }, { min: 20, premium: 1.9 }],
    blurb: "Same ounce, tired look. Spots, milk, bag marks. Priced to move, still an Eagle."
  }
];

AL.findProduct = function (idOrSlug) {
  if (!idOrSlug) return null;
  const key = String(idOrSlug).toLowerCase();
  return AL.products.find((p) => p.id === key || p.slug === key || p.sku.toLowerCase() === key) || null;
};
